const stateCodes = [
    {code: 'us-ak', name: 'Alaska'}, 
    {code: 'us-al', name: 'Alabama'}, 
    {code: 'us-ar', name: 'Arkansas'}, 
    {code: 'us-az', name: 'Arizona'}, 
    {code: 'us-ca', name: 'California'}, 
    {code: 'us-co', name: 'Colorado'},
    {code: 'us-ct', name: 'Connecticut'},
    {code: 'us-de', name: 'Delaware'},
    {code: 'us-fl', name: 'Florida'},
    {code: 'us-ga', name: 'Georgia'},
    {code: 'us-hi', name: 'Hawaii'},
    {code: 'us-ia', name: 'Iowa'},
    {code: 'us-id', name: 'Idaho'},
    {code: 'us-il', name: 'Illinois'},
    {code: 'us-in', name: 'Indiana'},
    {code: 'us-ks', name: 'Kansas'},
    {code: 'us-ky', name: 'Kentucky'},
    {code: 'us-la', name: 'Louisiana'},
    {code: 'us-ma', name: 'Massachusetts'},
    {code: 'us-md', name: 'Maryland'},
    {code: 'us-me', name: 'Maine'},
    {code: 'us-mi', name: 'Michigan'},
    {code: 'us-mn', name: 'Minnesota'},
    {code: 'us-mo', name: 'Missouri'},
    {code: 'us-ms', name: 'Mississippi'},
    {code: 'us-mt', name: 'Montana'},
    {code: 'us-nc', name: 'North Carolina'},
    {code: 'us-nd', name: 'North Dakota'},
    {code: 'us-ne', name: 'Nebraska'},
    {code: 'us-nh', name: 'New Hampshire'},
    {code: 'us-nj', name: 'New Jersey'},
    {code: 'us-nm', name: 'New Mexico'},
    {code: 'us-nv', name: 'Nevada'},
    {code: 'us-ny', name: 'New York'},
    {code: 'us-oh', name: 'Ohio'},
    {code: 'us-ok', name: 'Oklahoma'},
    {code: 'us-or', name: 'Oregon'},
    {code: 'us-pa', name: 'Pennsylvania'},
    {code: 'us-ri', name: 'Rhode Island'},
    {code: 'us-sc', name: 'South Carolina'},
    {code: 'us-sd', name: 'South Dakota'},
    {code: 'us-tn', name: 'Tennessee'},
    {code: 'us-tx', name: 'Texas'},
    {code: 'us-ut', name: 'Utah'},
    {code: 'us-va', name: 'Virginia'},
    {code: 'us-vt', name: 'Vermont'},
    {code: 'us-wa', name: 'Washington'},
    {code: 'us-wi', name: 'Wisconsin'},
    {code: 'us-wv', name: 'West Virginia'},
    {code: 'us-wy', name: 'Wyoming'}
];
export default stateCodes;
